package edu.maimonides.multimedia.shapes4learn.model;

/**
 * This empty class represents a Token generated by the lexical analyzer. It
 * will be implemented by the students according to the language and interpreter
 * requirements.
 * 
 * @author Matias Giorgio
 * 
 */
public class Token {

	// To be implemented.

}
